# Generated by Django 3.1.7 on 2021-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0311_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ext_auth_uid",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
